CI(actions): Move to manual pre-commit step
aristanetworks/ansible-cvp pull request #435
Opened 2022-01-04 16:57 UTC by titom73

## Change Summary

Since pre-commit GH action is marked as deprecated, CI will run
a generic script action to execute pre-commit in version indicated
requirements-dev.txt

URL: https://github.com/pre-commit/action

## Related Issue(s)

Fixes issue #432

## Component(s) name

Github Action

## Proposed changes

Implement manual `run` section for pre-commit in CI files.

## How to test

Check Action page

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-01-05 09:43 UTC, titom73 commented
CI error is related to ansible-test sanity result from older PR. A New PR is going to be opened to fix these errors

2022-01-06 14:29 UTC, mtache requested changes

2022-01-06 14:29 UTC, mtache commented on .github/workflows/pull-request-management.yml
> +          echo "PY_COLORS=1" >> $GITHUB_ENV
According to [this line](https://github.com/pre-commit/pre-commit/blob/master/pre_commit/color.py#L103) or [this doc](https://pre-commit.com/#command-line-interface) PY_COLORS is not consumed by pre-commit (like it is by molecule or pytest). You should use the following instead:
```suggestion
          echo "PRE_COMMIT_COLOR =always" >> $GITHUB_ENV
```

2022-01-06 14:29 UTC, mtache commented on .github/workflows/pull-request-management.yml
> +          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
Is there any ansible running in this job ? I think this line can be removed
 ```suggestion
```

2022-01-06 14:29 UTC, mtache commented on .github/workflows/pull-request-management.yml
> +          git branch -a
For clarity of workflow logs, I suggest to remove this line unless there is a need I missed.
```suggestion
```

2022-01-06 14:33 UTC, mtache commented on .github/workflows/pull-request-management.yml
> +          echo "PY_COLORS=1" >> $GITHUB_ENV
You should also use `--color always` argument to pre-commit command. Actually this would be better since you will have one less step in your job.

2022-01-06 15:01 UTC, mtache approved these changes

2022-01-06 15:17 UTC, merged