Fix (cv facts v3)  make image bundle name key usage consistent
aristanetworks/ansible-cvp pull request #513
Opened 2022-09-09 11:31 UTC by colinmacgiolla

## Change Summary

The `cv_facts_v3` was providing information (facts) about the software image bundle assigned to the container or device. The current implementation used `image_bundle` as the key. This is not compatible with the container/device schema, and inconsistent in usage.

This PR updates `cv_facts_v3` to provide the image bundle, using the `imageBundle` key, and updates the container schema to have the `imageBundle` as a string

## Related Issue(s)

Fixes #508 

## Component(s) name

`arista.cvp.cv_facts_v3`
`schema/v3.py`

## Proposed changes
Change is from `image_bundle: <name of image bundle` to `imageBundle: <name of image bundle>` for both devices and containers.

## How to test

```yaml
- name: container topology creation
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    # Container definition
    containers_provision:
        Undefined:
            configlets: []
            imageBundle: EOS-4.25.4M
            parentContainerName: Tenant
        containerA:
            configlets:
            - configletA1
            - configletA2
            imageBundle: ''
            parentContainerName: Tenant
        containerB:
            configlets:
            - configletB1
            - configletB2
            imageBundle: ''
            parentContainerName: containerA

  tasks:
    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: '{{containers_provision}}'
```

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-09-12 17:35 UTC, sugetha24 requested changes
Would you be able to add an example playbook that feeds the output of `cv_facts_v3` with the `imageBundle` keyword in it as an input to `cv_container_v3` and `cv_device_v3` ?

2022-09-18 21:57 UTC, sugetha24 approved these changes

2022-09-26 22:20 UTC, sugetha24 approved these changes

2022-10-13 20:41 UTC, sugetha24 approved these changes

2022-10-13 21:01 UTC, noredistribution approved these changes
LGTM!

2022-10-13 21:24 UTC, merged