Fix(cv_device_v3): Implement device image check mode
aristanetworks/ansible-cvp pull request #571
Opened 2022-12-21 09:38 UTC by colinmacgiolla

## Change Summary

So it looks like, for the most part the `cv_device_v3` completely ignored if check mode was set or not, which is not great. The recent support for image bundles made this more painful, and triggered issue #551 

## Related Issue(s)

Fixes #551 

## Component(s) name

`arista.cvp.cv_device_v3`

## Proposed changes
No changes to schema - we just block any API calls that would actually make changes on CVP with fake success. Anything going wrong before that point will fail as expected, so in theory this should be it.

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly. (check the box if not applicable)
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-02-03 17:44 UTC, sugetha24 requested changes

2023-02-03 17:44 UTC, sugetha24 commented on ansible_collections/arista/cvp/plugins/module_utils/device_tools.py
> +                    MODULE_LOGGER.warning('[check_mode] - Fake decomissioning of device %s', device.hostname)
I believe we should check for `check_mode` before the call on this line:
https://github.com/aristanetworks/ansible-cvp/blob/ebcc2ebee58adc93d47938be219e5f397e6dc1c5/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py#L1690

2023-02-07 10:23 UTC, colinmacgiolla commented on ansible_collections/arista/cvp/plugins/module_utils/device_tools.py
> +                    MODULE_LOGGER.warning('[check_mode] - Fake decomissioning of device %s', device.hostname)
Agreed - I was checking on the else loop

2023-02-07 10:51 UTC, colinmacgiolla commented on ansible_collections/arista/cvp/plugins/module_utils/device_tools.py
> +                    MODULE_LOGGER.warning('[check_mode] - Fake decomissioning of device %s', device.hostname)
Looks like something broke in the CI/CD pipeline :(

2023-02-23 22:42 UTC, sugetha24 approved these changes

2023-02-23 22:43 UTC, merged